services:
  deformbot:
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: deformbot
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "pgrep", "-f", "deform_bot.py"]  # checks if python process runs
        interval: 30s
        timeout: 10s
        retries: 3
      env_file:
        - .env
      environment:
        - MAGICK_THREAD_LIMIT=0   # use all available cores
      volumes:
        - .env:/deformbot/discord/.env
        - ${OUTPUT_PATH}:${OUTPUT_PATH}
      command: python3 deform_bot.py
      image: deformbot-1:latest
